---
all:
  children:
    nameservers:
      hosts:
        dhcp1.cnv.massopen.cloud:
        dhcp2.cnv.massopen.cloud:
      vars:
        ansible_user: root
    provisioner:
      vars:
        ansible_user: kni
        manage_dns: true
      hosts:
        provisioner.cnv2.massopen.cloud:
          ipmi_host: 10.0.5.13
          baremetal_ip: "192.12.185.140/24"
          baremetal_mac: "00:0f:53:0d:cd:31"
          provisioning_mac: "00:0f:53:0d:cd:30"
    openshift:
      vars:
        ansible_user: core
        ansible_python_interpreter: /usr/libexec/platform-python
        manage_dns: true
      hosts:
        openshift-master-0.cnv2.massopen.cloud:
          ipmi_host: 10.0.15.2
          baremetal_ip: 192.12.185.145
          baremetal_mac: d4:ae:52:94:d5:a5
          provisioning_mac: d4:ae:52:94:d5:a3
        openshift-master-1.cnv2.massopen.cloud:
          ipmi_host: 10.0.17.36
          baremetal_ip: 192.12.185.146
          baremetal_mac: d4:ae:52:98:15:0f
          provisioning_mac: d4:ae:52:98:15:0d
        openshift-master-2.cnv2.massopen.cloud:
          ipmi_host: 10.0.3.6
          baremetal_ip: 192.12.185.147
          baremetal_mac: 90:b1:1c:21:af:4a
          provisioning_mac: 90:b1:1c:21:af:48
        openshift-worker-0.cnv2.massopen.cloud:
          ipmi_host: 10.0.3.5
          baremetal_ip: 192.12.185.148
          baremetal_mac: d4:ae:52:98:22:27
          provisioning_mac: d4:ae:52:98:22:25
        openshift-worker-1.cnv2.massopen.cloud:
          ipmi_host: 10.0.17.38
          baremetal_ip: 192.12.185.149
          baremetal_mac: 90:b1:1c:21:96:3b
          provisioning_mac: 90:b1:1c:21:96:39
